server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bitest?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  #允许循环包依赖
  main:
    allow-circular-references: true

#配置mybatis实体与xml映射
mybatis:
  mapper-locations: classspath:mapper/*.xml
  type-aliases-package: com.springboot.entity

#配置分页插件
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql